// Code generated by qtc from "login.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/api/dashboard/templates/login.qtpl:1
package templates

//line internal/api/dashboard/templates/login.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/api/dashboard/templates/login.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/api/dashboard/templates/login.qtpl:1
func StreamLogin(qw422016 *qt422016.Writer, goctionVersion string) {
//line internal/api/dashboard/templates/login.qtpl:1
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en" class="has-background-black-bis">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Goction - Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"></script>
    <style>
        body, html {
            height: 100%;
        }
        .hero.is-fullheight {
            min-height: 100vh;
        }
        .input {
            background-color: #363636;
            color: #fff;
            border-color: #585858;
        }
        .input:focus {
            border-color: #3273dc;
        }
        .input::placeholder {
            color: #b5b5b5;
        }
    </style>
</head>
<body class="has-background-black-bis">
    <section class="hero is-fullheight">
        <div class="hero-body">
            <div class="container">
                <div class="columns is-centered">
                    <div class="column is-5-tablet is-4-desktop is-3-widescreen">
                        <div class="box has-background-black-ter">
                            <figure class="image is-96x96 mb-5" style="margin: 0 auto;">
                                <img src="https://goction.github.io/images/goction.png" alt="Goction Logo">
                            </figure>
                            <h1 class="title has-text-centered has-text-light">Goction Dashboard</h1>
                            <form method="POST" action="/login">
                                <div class="field">
                                    <label class="label has-text-light">Username</label>
                                    <div class="control has-icons-left">
                                        <input class="input" type="text" name="username" required placeholder="Enter your username">
                                        <span class="icon is-small is-left">
                                            <i class="fas fa-user"></i>
                                        </span>
                                    </div>
                                </div>
                                <div class="field">
                                    <label class="label has-text-light">Password</label>
                                    <div class="control has-icons-left">
                                        <input class="input" type="password" name="password" required placeholder="Enter your password">
                                        <span class="icon is-small is-left">
                                            <i class="fas fa-lock"></i>
                                        </span>
                                    </div>
                                </div>
                                <div class="field">
                                    <div class="control">
                                        <button class="button is-primary is-fullwidth" type="submit">Login</button>
                                    </div>
                                </div>
                            </form>
                            <div class="has-text-centered mt-4">
                                <p class="has-text-light">Goction version: `)
//line internal/api/dashboard/templates/login.qtpl:67
	qw422016.E().S(goctionVersion)
//line internal/api/dashboard/templates/login.qtpl:67
	qw422016.N().S(`</p>
                                <a href="https://goction.github.io" target="_blank" class="has-text-primary">Documentation</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>
`)
//line internal/api/dashboard/templates/login.qtpl:78
}

//line internal/api/dashboard/templates/login.qtpl:78
func WriteLogin(qq422016 qtio422016.Writer, goctionVersion string) {
//line internal/api/dashboard/templates/login.qtpl:78
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/api/dashboard/templates/login.qtpl:78
	StreamLogin(qw422016, goctionVersion)
//line internal/api/dashboard/templates/login.qtpl:78
	qt422016.ReleaseWriter(qw422016)
//line internal/api/dashboard/templates/login.qtpl:78
}

//line internal/api/dashboard/templates/login.qtpl:78
func Login(goctionVersion string) string {
//line internal/api/dashboard/templates/login.qtpl:78
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/api/dashboard/templates/login.qtpl:78
	WriteLogin(qb422016, goctionVersion)
//line internal/api/dashboard/templates/login.qtpl:78
	qs422016 := string(qb422016.B)
//line internal/api/dashboard/templates/login.qtpl:78
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/api/dashboard/templates/login.qtpl:78
	return qs422016
//line internal/api/dashboard/templates/login.qtpl:78
}
